[global_test_settings]
name = Test 1
tools = iperf, ss

[iperf_server]
port = 5201
interval = 1
format = m
json = true
logfile = output.log
verbose = true

deamon = true

[iperf_client]
#port = 5201
interval = 0.5
#format = m
json = true
logfile = output.log
#verbose = true
duration = 5
# bytes = None
host = localhost